---
version: "3"
services:
 devopsdb:
   container_name: devopsdb
   image: jyothisaimekala/jts:dbimage
   ports:
     - "3306:3306"

 application:
   image: jyothisaimekala/jts:appimage
   container_name: appcontainer
   ports:
     - "1234:8080"
   depends_on:
     - "devopsdb"
